export const ERROR_TOAST_DURATION_MS = 5_000;
export const SUCCESS_TOAST_DURATION_MS = 500;
export const RECIPE_SAVE_TOAST_DURATION_MS = SUCCESS_TOAST_DURATION_MS;
export const SINGLE_IMPORT_ERROR_TOAST_DURATION_MS = 10_000;
export const IMPORT_ERROR_TOAST_DURATION_MS = 60_000;
